noninteractive-tradefed: change to work with python3
This commit change to use python3 for tradefed-runner.py,
and drop the packages installation as they will be installed
on the Linaro Ubuntu20.04 based docker image side which will have
python3 installed as the default python:
    https://hub.docker.com/r/linaro/lava-android-postprocess
Or the user needs to prepare the packages on the host first.

The background is that, the latest AOSP vts package needs to
have python3.8+ to run the vts_kernel_proc_file_api_test module
after the following commit:
    https://android.googlesource.com/platform/test/vts-testcase/vndk/+/6f09ccb69d553a48dd231635a06889af26ff545f%5E%21/#F3

Otherwise, the following error will be reported:
    07-26 12:45:26 I/ModuleListener: [66/67] cbe37e vts_kernel_proc_file_api_test __main__.VtsKernelProcFileApiTest#test_ProcZoneInfoTest FAILURE: Traceback (most recent call last):
      File "/tmp/Soong.python_p2c4wyvb/vts_kernel_proc_file_api_test.py", line 277, in test
        test_object.set_api_level(self.dut)
      File "/tmp/Soong.python_p2c4wyvb/proc_tests/KernelProcFileTestBase.py", line 140, in set_api_level
        self.api_level = dut.getLaunchApiLevel(strict=False)
      File "/tmp/Soong.python_p2c4wyvb/vts/testcases/vndk/utils.py", line 147, in getLaunchApiLevel
        return self.GetLaunchApiLevel()
      File "/tmp/Soong.python_p2c4wyvb/vts/testcases/vndk/utils.py", line 122, in GetLaunchApiLevel
        level_str = self._GetProp("ro.product.first_api_level")
      File "/tmp/Soong.python_p2c4wyvb/vts/testcases/vndk/utils.py", line 94, in _GetProp
        out, err, return_code = self.Execute("getprop", name)
      File "/tmp/Soong.python_p2c4wyvb/vts/testcases/vndk/utils.py", line 68, in Execute
        cmd = ["adb", "-s", self._serial_number, "shell", shlex.join(args)]
    AttributeError: module 'shlex' has no attribute 'join'

Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>