tradefed/noninteractive-tradefed: use jdk8 and remove _JAVA_OPTIONS
1. the _JAVA_OPTIONS confuses the java version check in cts/vts
   and as cts/vts try to allocate more memory in their scripts following:
     https://android.googlesource.com/platform/test/vts/+/refs/heads/master/tools/vts-tradefed/etc/vts-tradefed#187
     https://android.googlesource.com/platform/test/suite_harness/+/refs/heads/master/tools/cts-tradefed/etc/cts-tradefed#133
   there is no meaning to set _JAVA_OPTIONS any more.

2. fixed to use jdk8 for vts/cts test
   as the installed openjdk-9-jdk-headless would cause following error with vts test:

   Using commandline arguments as starting command: [run, commandAndExit, vts-kernel, --module, VtsKernelLinuxKselftest]
   java.lang.reflect.InaccessibleObjectException: Unable to make member of class sun.reflect.annotation.AnnotationInvocationHandler accessible:  module java.base does not export sun.reflect.annotation to unnamed module @3224f60b
    at sun.reflect.Reflection.throwInaccessibleObjectException(java.base@9-internal/Reflection.java:420)
    at java.lang.reflect.AccessibleObject.checkCanSetAccessible(java.base@9-internal/AccessibleObject.java:174)
    at java.lang.reflect.Field.checkCanSetAccessible(java.base@9-internal/Field.java:170)
    at java.lang.reflect.Field.setAccessible(java.base@9-internal/Field.java:164)
    at com.android.tradefed.config.OptionSetter.updateOptionChangedField(OptionSetter.java:556)
    at com.android.tradefed.config.OptionSetter.setFieldValue(OptionSetter.java:538)
    at com.android.tradefed.config.OptionSetter.setOptionValue(OptionSetter.java:414)
    at com.android.tradefed.config.OptionSetter.setOptionValue(OptionSetter.java:359)
    at com.android.compatibility.common.tradefed.testtype.suite.CompatibilityTestSuite.<init>(CompatibilityTestSuite.java:74)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(java.base@9-internal/Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(java.base@9-internal/NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(java.base@9-internal/DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(java.base@9-internal/Constructor.java:453)
    at java.lang.Class.newInstance(java.base@9-internal/Class.java:550)
    at com.android.tradefed.config.ConfigurationDef.createObject(ConfigurationDef.java:423)
    at com.android.tradefed.config.ConfigurationDef.createConfiguration(ConfigurationDef.java:252)
    at com.android.tradefed.config.ConfigurationFactory.internalCreateConfigurationFromArgs(ConfigurationFactory.java:573)
    at com.android.tradefed.config.ConfigurationFactory.createConfigurationFromArgs(ConfigurationFactory.java:495)
    at com.android.tradefed.command.CommandScheduler.createConfiguration(CommandScheduler.java:1191)
    at com.android.tradefed.command.CommandScheduler.internalAddCommand(CommandScheduler.java:1201)
    at com.android.tradefed.command.CommandScheduler.addCommand(CommandScheduler.java:1146)
    at com.android.tradefed.command.CommandScheduler.addCommand(CommandScheduler.java:1138)
    at com.android.tradefed.command.Console$27.run(Console.java:736)
    at com.android.tradefed.command.Console$27.run(Console.java:727)
    at com.android.tradefed.command.Console.executeCmdRunnable(Console.java:926)
    at com.android.tradefed.command.Console.run(Console.java:1028)
    at com.android.compatibility.common.tradefed.command.CompatibilityConsole.run(CompatibilityConsole.java:104)
   07-10 04:46:57 V/LogRegistry: Saved log to /tmp/tradefed_global_log_6919477904182546528.txt

    after the change here:
    https://android-review.googlesource.com/c/platform/tools/tradefederation/+/1010290/3/src/com/android/tradefed/config/OptionSetter.java

Change-Id: Ib972a8c3ca8c3e9b6ea2a07e03b42e357d487b34
Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>