Update patch set 1
Patch Set 1:

(1 comment)

> Hi Riku,
 > 
 > No package qemu-efi available on CentOS.
 > 
 > [root@c14n1 linux]# yum install qemu-efi
 > Loaded plugins: fastestmirror
 > Loading mirror speeds from cached hostfile
 > No package qemu-efi available.
 > Error: Nothing to do
 > [root@c14n1 linux]# cat /etc/redhat-release
 > CentOS Linux release 7.2.1603 (AltArch)
 > [root@c14n1 linux]# uname -a
 > Linux c14n1 4.2.0-0.31.el7.1.aarch64 #1 SMP Fri Oct 28 15:29:14 UTC
 > 2016 aarch64 aarch64 aarch64 GNU/Linux
 > [root@c14n1 linux]#

apt is used, not yum. so we assume we're running a debian based system.

Patch-set: 1
Reviewer: Fathi Boudra <1000009@f33910f19b7abb192b83adbd000000bf>
Label: Code-Review=0