Update patch set 1
Patch Set 1: Code-Review-1

"Build Failed 

https://ci.linaro.org/jenkins/job/qa-test-definitions-sanity-check/810/ : [OUTPUT]: <<<
* SHELLCHECK: [FAILED]: manual/generic/linux/openssh.spec.patch
* SHELLCHECK: [OUTPUT]:
 
 In manual/generic/linux/openssh.spec.patch line 1:
 diff -Narub a/openssh.spec b/openssh.spec
 ^-- SC2148: Tips depend on target shell and yours is unknown. Add a shebang.



* YAMLVALID: [FAILED]: manual/generic/linux/openssh.yaml



 yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 65, column 24:
              BuildRequires: util-linux, groff
                           ^
>>>"

Patch-set: 1
Label: Code-Review=-1