test-runner: fix UnicodeEncodeError with Python2
decode('utf-8') was added to strip off b' prefix from Python3's output.
The current code also runs that with Python2, it worked in most cases
some how. Howerver, once test-runner output redirectory used, it hits
UnicodeEncodeError when running tests include wget download step like
ltp and libhugetlbfs tests.

Usage: python2 automated/utils/test-runner.py \
       -d automated/linux/libhugetlbfs/libhugetlbfs.yaml \
       -o /root/output/libhugetlbfs \
       > test-runner-stdout.log 2> test-runner-stderr.log

Error: UnicodeEncodeError: 'ascii' codec can't encode character
       u'\u2018' in position 11: ordinal not in range(128)

This patch detects Python version at runtime, then,
* Uses decode('utf-8') for Python3 pexpect output to remove prefix 'b'.
* Uses subprocess getoutput() instead of check_output() for Python3 to
  get normal string.

Change-Id: Ie52192787a8e4cd0550e1cd05b1ca53a02f4ab63
Signed-off-by: Chase Qi <chase.qi@linaro.org>